import { z } from 'zod';

// CREATE DTO for vehicles — validated business fields only.
export const CreateVehiclesSchema = z.object({
  companyTag: z.number().optional().nullable(),
  baseOfficeId: z.number(),
  vendorId: z.number(),
  rcNum: z.string().optional().nullable(),
  vehicleNum: z.string().optional().nullable(),
  vehicleOwnership: z.string().optional().nullable(),
  ownerType: z.string().optional().nullable(),
  bodyType: z.string().optional().nullable(),
  make: z.string().optional().nullable(),
  model: z.string().optional().nullable(),
  specification: z.string().optional().nullable(),
  subSpecification: z.string().optional().nullable(),
  fuelType: z.string().optional().nullable(),
  gvw: z.number().optional().nullable(),
  capacity: z.number().optional().nullable(),
  gvwCapacityUnit: z.string().optional().nullable(),
  length: z.number().optional().nullable(),
  width: z.number().optional().nullable(),
  height: z.number().optional().nullable(),
  lwhUnit: z.string().optional().nullable(),
  vehicleContactMobile1: z.string().optional().nullable(),
  vehicleContactMobile2: z.string().optional().nullable(),
  rtoRegExpiry: z.coerce.date().optional().nullable(),
  rcUrl: z.string().optional().nullable(),
  insurancePolicyNum: z.string().optional().nullable(),
  insuranceExpiry: z.coerce.date().optional().nullable(),
  insuranceDocUrl: z.string().optional().nullable(),
  fitnessCertNum: z.string().optional().nullable(),
  fitnessCertExpiry: z.coerce.date().optional().nullable(),
  fitnessCertUrl: z.string().optional().nullable(),
  permitExpiry: z.coerce.date().optional().nullable(),
  pollutionExpiry: z.coerce.date().optional().nullable(),
  gpsDeviceId: z.string(),
  manufacturingYear: z.string().optional().nullable(),
  vehicleStatus: z.number().optional().nullable(),
  currentOfficeId: z.number(),
  active: z.boolean().optional().nullable(),
  status: z.string(),
  note: z.string().optional().nullable(),
});

export type CreateVehiclesDto = z.infer<typeof CreateVehiclesSchema>;