import { z } from 'zod';

// CREATE DTO for customer — validated business fields only.
export const CreateCustomerSchema = z.object({
  companyTag: z.number().optional().nullable(),
  parentId: z.number().optional().nullable(),
  primaryServicingOfficeId: z.number(),
  code: z.string(),
  name: z.string(),
  nameReg: z.string().optional().nullable(),
  cType: z.string().optional().nullable(),
  cSubtype: z.string().optional().nullable(),
  customerType: z.string().optional().nullable(),
  customerGroup: z.string().optional().nullable(),
  industryType: z.string().optional().nullable(),
  paymentTypes: z.record(z.any()).optional().nullable(),
  mobile: z.string(),
  telNum: z.string().optional().nullable(),
  email: z.string().email().optional().nullable(),
  billingContactPerson: z.string().optional().nullable(),
  billingMobile: z.string().optional().nullable(),
  billingEmail: z.string().email().optional().nullable(),
  billingAddress: z.string().optional().nullable(),
  billingAddressReg: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  state: z.string().optional().nullable(),
  district: z.string().optional().nullable(),
  taluka: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  pincode: z.string().optional().nullable(),
  address: z.string().optional().nullable(),
  addressReg: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  panNum: z.string().optional().nullable(),
  gstNum: z.string().optional().nullable(),
  creditLimit: z.number().optional().nullable(),
  paymentTerms: z.string().optional().nullable(),
  billingCycle: z.string().optional().nullable(),
  accountManagerId: z.number(),
  otherServicingOffices: z.record(z.any()).optional().nullable(),
  erpEntryDate: z.coerce.date().optional().nullable(),
  active: z.boolean().optional().nullable(),
});

export type CreateCustomerDto = z.infer<typeof CreateCustomerSchema>;